version: '3.3'

services:
  postgres:
    image: 'postgres:12.0'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 65432:5433
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
        - postgres
  spring-boot-docker-container:
    image: 'springboot-docker-container'
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      -   postgres
volumes:
  postgres-data:

networks:
  postgres:
    external: true